package com.inspur.vista.labor.cp.util;

public enum ErrorCodeEnum {

    P_SUCCESS("P00000", "操作成功"),
    P_SYS_ERROR("P10001", "系统异常"),
    P_SERVICE_PAUSE("P10002", "服务超时/暂停"),
    P_DB_TIMEOUT("P10003", "数据库链接超时"),
    P_DB_OPERATOR_EXCEPTION("P10004", "数据库操作异常"),
    P_IP_RESTRICT("P10005", "IP受限不能请求该资源"),
    P_INVALID("P10006", "非法请求"),
    P_RES_NOT_FOUND("P10007", "请求资源不存在"),
    P_RES_UNAUTHORIZED("P10008", "请求资源未授权"),
    P_RPC_TIMEOUT("P10009", "RPC调用超时"),
    P_RPC_EXCEPTION("P10000", "RPC调用异常"),
    P_RPC_SRV_NOT_FOUND("P10011", "未找到RPC服务"),
    P_REQUEST_FREQUENTLY("P10012", "请求过于频繁"),
    P_GET_ACCESS_TOKEN_FAILURE("P10013", "获取访问票据失败"),
    P_TASK_TYPE_NOT_EXIST("P10014", "任务类型不存在"),
    S_NAME_OR_PWD_ERROR("S20001", "用户名或密码错误"),
    S_ACCOUNT_LOCK("S20002", "账号已锁定"),
    S_CODE_ERROR("S20003", "验证码不正确"),
    S_REQ_PARAM_COUNT_ERROR("S20004", "请求参数数量不正确"),
    S_REQ_PARAM_ERROR("S21004", "请求参数不正确"),
    S_REQ_PARAM_NULL("S20005", "必填参数为空"),
    S_REQ_PARAM_FOMAT_ERROR("S20006", "参数的格式不合法"),
    S_REQ_PARAM_INVALID_NUMBER("S20007", "非法数字"),
    S_TYPE_NOT_SUPPORT("S20008", "不支持的类型"),
    S_FILE_TOO_LARGE("S20009", "上传文件大小太大"),
    S_FILE_IS_ZERO("S20019", "上传文件大小为零"),
    S_FILE_EXIST("S20029", "文件已经存在"),
    S_WORDS_TOO_LONG("S20010", "输入的文字太长"),
    S_RECORD_NOT_EXIST("S20011", "更新记录不存在"),
    S_UNAUTHOR_BIZ_CODE("S20012", "业务编码没有授权"),
    S_ES_NOT_INDEX("S20010", "ES索引不存在"),
    S_ES_HAS_INDEX("S20011", "ES索引已存在"),
    S_ES_NOT_TYPE("S20012", "ES类型不存在"),
    S_ES_HAS_TYPE("S20013", "ES类型已存在"),
    S_DB_NOT_SUPPORT_TYPE("S20014", "不支持的数据库类型"),
    S_DB_SCHEMA_NONE("S20015", "数据库Schema为空"),
    S_DB_CONFIG_NONE("S20016", "数据库配置信息为空"),
    S_RESOURCE_ILLEGAL("S10017", "访问资源不合法"),
    S_CREDIT_CODE_EXIST("S10018", "此社会信用代码已经注册"),
    S_EXIST("S10019", "系统中已存在"),
    S_UAC_ACCESS_TOKEN_INVALID("S21001", "无效的access token"),
    S_UAC_USER_INVALID("S21002", "用户无效"),
    S_UAC_USER_LOCKED("S21003", "用户已锁定"),
    S_UAC_USER_NOT_REGISTERED("S21005", "用户尚未注册，请先注册"),
    S_UAC_REFRESH_TOKEN_INVALID("S21006", "无效的refresh token"),
    S_UAC_PHONE_NOT_REGISTER("S21007", "手机号未注册"),
    S_UAC_PHONE_HAS_REGISTER("S21008", "手机号已注册"),
    S_UAC_USERNAME_NOT_REGISTER("S21009", "用户名未注册"),
    S_UAC_USERNAME_HAS_REGISTER("S21010", "用户名已注册"),
    S_UAC_REGISTER_CODE_ERROR("S21011", "注册码错误"),
    S_UAC_VERSION_CODE_ERROR("S21012", "版本号错误"),
    S_UAC_PASSWORD_IS_INIT("S21013", "密码为初始密码，请修改密码"),
    S_UAC_TOKEN_REFRESH("S21014", "token已刷新"),
    S_UAC_AUTH_CODE_INVALID("S21015", "授权码无效"),
    S_EXAM_TIME_OUT("S22001", "考试时间已过"),
    S_QLGH_NO_ACTIVITY("S31001", "无此活动"),
    S_QLGH_ERROR_ACTIVITY("S31002", "活动类型错误"),
    S_QLGH_REPEAT_VOTE("S31003", "请勿重复投票"),
    S_QLGH_ERROR_PARAM("S31004", "参数错误"),
    S_QLGH_ERROR_REGISTER_PHONE("S31005", "手机号格式错误"),
    S_QLGH_SMS_API_ERROR("S31006", "短信发送异常"),
    S_QLGH_ACTIVITY_CLOSE("S31007", "活动已结束"),
    S_QLGH_SMS_CHECK_FAIL("S31008", "短信验证失败"),
    S_QLGH_SMS_CHECK_OVERRIDE("S31009", "短信验证码已过期"),
    S_QLGH_NO_PASSWORD("S31010", "未填写密码"),
    S_QLGH_NO_PHONE("S31011", "未填写手机号"),
    S_QLGH_NO_CODE("S31012", "注册时未填写验证码"),
    S_QLGH_LOGIN_PHONE_NOT_EXISTS("S31013", "登录时手机号不存在"),
    S_QLGH_PASSWORD_ERROR("S31014", "登录时密码错误"),
    S_QLGH_AUTHENTICATION_NAME("S31015", "认证时姓名错误"),
    S_QLGH_AUTHENTICATION_IDCARD("S31016", "认证时身份证号错误"),
    S_QLGH_AUTHENTICATION_FAIL("S31017", "调用工会服务认证未通过"),
    S_QLGH_TOKEN_CHECK_FAILED("S31018", "token验证失败"),
    S_QLGH_UN_OPEN("S31019", "活动未开始"),
    S_QLGH_EXCEPTION_ACTIVITY("S31020", "活动异常"),
    S_QLGH_REPEAT_ERROR("S31021", "已存在相同处理"),
    S_QLGH_CONRIFM_FAIL("S31022", "确认工会信息异常"),
    S_QLGH_EXCEPTION_REPEAT_JOIN("S31023", "你已参与过该活动"),
    S_QLGH_TICKETS_NO_HAVE("S31024", "券已领完"),
    S_QLGH_EXCEPTION_TICKETS("S31025", "抢券失败"),
    S_QLGH_EXCEPTION_OPERATION("S31026", "操作失败"),
    S_QLGH_EXCEPTION_TICKETS_GONE("S31027", "你已经领取过优惠券"),
    S_QLGH_NO_AUTHENTICATION("S31028", "不是认证用户，无法参与"),
    S_QLGH_EXCEPTION_NO_NUM("S31029", "参与次数已达上限"),
    S_QLGH_EXCEPTION_SYS_ERROR("S31030", "人实在太多了，请歇一会，再重试！"),
    S_QLGH_JOIN_NUM_FUL("S31031", "活动名额已满，谢谢参与！"),
    S_QLGH_EXCEPTION_LOGON_ERROR("S31032", "您还未登录,请先去登录！"),
    S_QLGH_EXCEPTION_DIVISION_ERROR("S31033", "您的区划信息有误,请重新选择区划信息！"),
    C_VALUE_NULL("C00001", "为空"),
    C_VALUE_TOO_LONG("C00002", "长度太长"),
    C_VALUE_TOO_SHORT("C00003", "长度太短"),
    C_VALUE_FORMAT_INVALID("C00004", "格式不合法"),
    C_LOST("C00005", "缺失"),
    C_NOT_DIGIT("C00006", "非法数字"),
    C_NOT_ZERO("C00007", "非零数字"),
    C_DICT_INVALID("C00008", "非法选项"),
    C_MEMBER_NULL("C00009", "会员为空"),
    C_WORKER_COUNT_LESS_THAN_MEMBER("C00010", "会员数超过了职工人数"),
    C_MIGRANTWORKER_COUNT_LESS_THAN_MEMBER("C00011", "农民工会员数超过了农民工人数"),
    C_WORKER_COUNT_LESS_THAN_MIGRANT("C00012", "农民工职工人数超过了职工人数"),
    C_ID_CARD_REPEAT("C00013", "记录重复"),
    C_INVALID_RANGE("C00014", "无效的数值范围"),
    C_ID_CARD_INVALID("C00015", "证件号码无效"),
    C_FILE_ERROR("C00016", "糟糕了!您的采集文件错误太多，请仔细检查"),
    C_CELL_FORMAT_ERROR("C00017", "单元格格式错误"),
    C_ID_CARD_HAS_AUTHENTICATION("C00018", "该身份证号已认证"),
    C_ID_CARD_NAME_INCONFORMITY("C00019", "姓名和身份证号不匹配"),
    C_DELETE_MEMBER_FAILED("C00020", "删除会员失败"),
    C_UNDER_ORGAN_EXIST("C00021", "当前组织下存在下级组织"),
    C_UNDER_MEMBER_EXIST("C00022", "当前组织下存在工会会员"),
    C_PARTENT_ORGAN_NOT_EXIST("C00023", "上级组织不存在"),
    C_CURRENT_ORGAN_HAS_EXIST("C00024", "当前组织已在目标组织下"),
    C_MEMBER_NOT_EXIST("C00025", "会员不存在"),
    C_SUCCESS("C00000", "检查通过"),
    B_NEED_PAY("P30001", "需要支付");

    private String msg;
    private String code;

    private ErrorCodeEnum(String code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public String getMsg() {
        return this.msg;
    }

    public String getCode() {
        return this.code;
    }
}
